/**
 * P4.82 — the committed `headshoulders-{main,mount}.db` fixture builder: the
 * substrate for `headshoulders_backfill_tier3_equivalence` (the
 * `CHARACTER_HEADSHOULDERS_BACKFILL` job handler) and
 * `headshoulders_backfill_enqueue_equivalence` (the boot-time scan + the
 * dedupe-on-enqueue queue helper).
 *
 * Measured before it was written (the order's §Fixtures question): the
 * committed `character-generators-{main,mount}.db` pair carries exactly TWO
 * characters — Mira (a full `physicalDescription` that ALREADY has a
 * `headAndShouldersPrompt`) and Nix (`physicalDescription: null`). It has no
 * vault-less character, no whitespace-only prompt or seed, no eligible
 * character, no already-PENDING backfill job, and only ONE user (so the
 * no-profile / no-API-key / local-selection arms are unreachable). A new pair
 * is therefore the expected outcome, exactly as the order predicted.
 *
 * Bakes, via v4's REAL repositories (every id pinned except the vault-side
 * mount-point / link / blob ids, which are MINTED but baked into the committed
 * .db, so both differential sides read identical rows):
 *   - FOUR users, one per cheap-LLM resolution arm: `friday` (two connection
 *     profiles + one api key + a `chat_settings` row whose
 *     `cheapLLMSettings.defaultCheapProfileId` names the SECOND profile, so
 *     priority-1 selection is discriminating — a dropped chat-settings read
 *     picks the default-flagged first profile instead), `localop` (one OLLAMA
 *     profile → `isLocal` → the empty-string key), `keyless` (one OPENAI
 *     profile with NO `apiKeyId` → the null-key warn arm), `profileless` (no
 *     profiles at all → the no-profile warn arm),
 *   - ELEVEN characters, one per classification arm of the startup scan and of
 *     the handler (see the spec's names). `Vaultless Vera`'s vault pointer is
 *     NULLED after her physical description is written, which is the only way
 *     to make a character carry the *shape* of an eligible one and still fail
 *     the enqueuer's first gate.
 *
 * ⚠ Two measurements this fixture's first build settled, both recorded
 * rather than designed around:
 *   1. Provisioning a vault SCAFFOLDS `physical-prompts.json`, so every
 *      vault-linked character reads back a `physicalDescription` OBJECT (all
 *      tiers null) rather than `null`. The handler's `if (!pd) return` arm and
 *      the scan's `if (!pd) skipped++` arm are therefore reachable ONLY for a
 *      vault-LESS character — where the raw row leaves the managed field at
 *      its Zod default and the key reads back omitted. `Vaultless Vera` is
 *      that case on both sides; there is no separate "linked but no pd"
 *      shape to seed, because v4 cannot produce one.
 *   2. The vault's renderer owns `physicalDescription.name` (`"default"`)
 *      and its `createdAt`/`updatedAt`; the spec's `name` never survives. Both
 *      are BAKED into the committed .db, so they are deterministic comparands
 *      — but a rebuild moves the two timestamps, which is why this pair is
 *      committed and regenerated by nobody but this builder.
 *   - one already-PENDING `CHARACTER_HEADSHOULDERS_BACKFILL` job for
 *     `Pending Persimmon`, so the queue helper's dedupe answers
 *     `{isNew:false}` and the scan counts her as skipped.
 *
 * The `instance_settings` table is materialized EMPTY: the scan's
 * `headshoulders_backfill_enqueued_v1` gate reads it on both sides, and v4
 * would throw (→ the "treating as not-yet-run" warn) on a missing table where
 * v5's read would not — the P4.D130 lesson.
 *
 * Regenerate (Node 24, from the v4 checkout) + re-copy the committed .db files:
 *   N=~/.nvm/versions/node/v24.13.1/bin
 *   V5W=${V5W:-$HOME/source/quilltap-v5}
 *   cd ~/source/quilltap-server
 *   QT_FIXTURE_HS_MAIN=$V5W/crates/quilltap-web/tests/fixtures/headshoulders-main.db \
 *   QT_FIXTURE_HS_MOUNT=$V5W/crates/quilltap-web/tests/fixtures/headshoulders-mount.db \
 *     $N/node --import tsx $V5W/harness/oracle/fixtures/build-headshoulders-fixture.ts
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';

interface UserSpec { id: string; username: string; name: string }
interface ChatSettingsSpec { userId: string; cheapLLMSettings: Record<string, unknown> }
interface CharacterSpec {
  id: string;
  name: string;
  userId: string;
  dropVault?: boolean;
  pendingBackfillJobId?: string;
  physicalDescription: Record<string, unknown> | null;
}
interface Spec {
  testPepperBase64: string;
  seedTimestamp: string;
  frozenNowMs: number;
  missingCharacterId: string;
  users: UserSpec[];
  apiKeys: Array<Record<string, unknown>>;
  connectionProfiles: Array<Record<string, unknown>>;
  chatSettings: ChatSettingsSpec[];
  characters: CharacterSpec[];
}

async function main(): Promise<void> {
  const here = dirname(fileURLToPath(import.meta.url));
  const spec = JSON.parse(readFileSync(join(here, 'headshoulders.json'), 'utf8')) as Spec;

  const mainOut = process.env.QT_FIXTURE_HS_MAIN;
  const mountOut = process.env.QT_FIXTURE_HS_MOUNT;
  if (!mainOut || !mountOut) {
    throw new Error('QT_FIXTURE_HS_MAIN and QT_FIXTURE_HS_MOUNT must point at the .db files');
  }
  for (const out of [mainOut, mountOut]) {
    for (const suffix of ['', '-journal', '-wal', '-shm']) {
      const p = out + suffix;
      if (existsSync(p)) rmSync(p);
    }
  }

  const scratch = mkdtempSync(join(tmpdir(), 'qt-headshoulders-fixture-'));
  mkdirSync(join(scratch, 'data'), { recursive: true });

  process.env.ENCRYPTION_MASTER_PEPPER = spec.testPepperBase64;
  process.env.SQLITE_PATH = mainOut;
  process.env.SQLITE_MOUNT_INDEX_PATH = mountOut;
  process.env.QUILLTAP_DATA_DIR = scratch;
  delete process.env.SQLITE_WAL_MODE;
  process.env.LOG_LEVEL = 'error';

  const { initializeDatabase, ensureCollection, getCollection, closeDatabase } = await import(
    '@/lib/database/manager'
  );
  const { getRepositories } = await import('@/lib/repositories/factory');
  const { getRawMountIndexDatabase, closeMountIndexSQLiteClient } = await import(
    '@/lib/database/backends/sqlite/mount-index-client'
  );
  const { getRawDatabase } = await import('@/lib/database/backends/sqlite/client');
  const { CharacterSchema } = await import('@/lib/schemas/types');
  const { generateDDL } = await import('@/lib/database/schema-translator');
  const {
    DocMountPointSchema,
    DocMountFileSchema,
    DocMountDocumentSchema,
    DocMountFolderSchema,
    DocMountFileLinkSchema,
    DocMountChunkSchema,
  } = await import('@/lib/schemas/mount-index.types');
  const { ApiKeySchema } = await import('@/lib/schemas/profile.types');
  const { BackgroundJobSchema } = await import('@/lib/schemas/job.types');

  await initializeDatabase();
  await ensureCollection('characters', CharacterSchema);
  await ensureCollection('api_keys', ApiKeySchema);

  const midb = getRawMountIndexDatabase();
  if (!midb) throw new Error('mount-index DB handle unavailable');
  const ddl: Array<[string, unknown]> = [
    ['doc_mount_points', DocMountPointSchema],
    ['doc_mount_files', DocMountFileSchema],
    ['doc_mount_documents', DocMountDocumentSchema],
    ['doc_mount_folders', DocMountFolderSchema],
    ['doc_mount_file_links', DocMountFileLinkSchema],
    ['doc_mount_chunks', DocMountChunkSchema],
  ];
  for (const [name, schema] of ddl) {
    for (const sql of generateDDL(name, schema as never)) midb.exec(sql);
  }
  const { DocMountBlobsRepository } = await import(
    '@/lib/database/repositories/doc-mount-blobs.repository'
  );
  await new DocMountBlobsRepository().findByFileId('00000000-0000-4000-8000-000000000000');

  const maindb = getRawDatabase();
  if (!maindb) throw new Error('main DB handle unavailable');
  // v4 auto-creates `background_jobs` on the first enqueue; the Rust port does
  // not own DDL, so its fixture copy needs the table up front.
  for (const sql of generateDDL('background_jobs', BackgroundJobSchema as never)) {
    maindb.exec(sql);
  }
  // The scan's flag gate reads this on both sides — materialize it EMPTY so
  // "no flag" is the same nothing for v4 and v5 (the P4.D130 lesson).
  maindb.exec(
    'CREATE TABLE IF NOT EXISTS "instance_settings" ("key" TEXT PRIMARY KEY, "value" TEXT NOT NULL)',
  );

  const repos = getRepositories();
  const TS = spec.seedTimestamp;

  for (const u of spec.users) {
    await repos.users.create(
      { username: u.username, email: null, name: u.name } as never,
      { id: u.id, createdAt: TS, updatedAt: TS } as never,
    );
  }

  const apiKeyCol = await getCollection('api_keys');
  for (const key of spec.apiKeys) {
    const row = ApiKeySchema.parse({ ...key, createdAt: TS, updatedAt: TS });
    await apiKeyCol.insertOne(row as never);
  }
  for (const profile of spec.connectionProfiles) {
    const { id, ...rest } = profile as Record<string, unknown>;
    await repos.connections.create({ ...rest } as never, {
      id, createdAt: TS, updatedAt: TS,
    } as never);
  }

  for (const cs of spec.chatSettings) {
    await repos.chatSettings.create(
      { userId: cs.userId, cheapLLMSettings: cs.cheapLLMSettings } as never,
      { id: `d0000082-0000-4000-8000-${cs.userId.slice(-12)}`, createdAt: TS, updatedAt: TS } as never,
    );
  }

  for (const c of spec.characters) {
    await repos.characters.create(
      {
        name: c.name,
        userId: c.userId,
        title: null,
        identity: null,
        description: null,
        manifesto: null,
        personality: null,
        firstMessage: null,
        exampleDialogues: null,
        aliases: [],
        pronouns: null,
        controlledBy: 'llm',
        talkativeness: 0.5,
        isFavorite: false,
        npc: false,
        tags: [],
      } as never,
      { id: c.id, createdAt: TS, updatedAt: TS } as never,
    );
    if (c.physicalDescription) {
      await repos.characters.update(c.id, {
        physicalDescription: c.physicalDescription,
      } as never);
    }
    if (c.pendingBackfillJobId) {
      await repos.backgroundJobs.create(
        {
          userId: c.userId,
          type: 'CHARACTER_HEADSHOULDERS_BACKFILL',
          status: 'PENDING',
          payload: { characterId: c.id },
          priority: -1,
          attempts: 0,
          maxAttempts: 3,
          lastError: null,
          scheduledAt: TS,
          startedAt: null,
          completedAt: null,
        } as never,
        { id: c.pendingBackfillJobId, createdAt: TS, updatedAt: TS } as never,
      );
    }
  }

  // The vault-less shape: the physical description is written into the vault
  // FIRST (so the row is otherwise ordinary), then the pointer is cut. Nothing
  // above the raw column can reach the file afterwards, which is exactly what a
  // character the vault backfill has not yet reached looks like.
  for (const c of spec.characters.filter((x) => x.dropVault)) {
    maindb
      .prepare('UPDATE "characters" SET "characterDocumentMountPointId" = NULL WHERE "id" = ?')
      .run(c.id);
  }

  // Force the empty tables both sides' read paths touch into existence through
  // the repos' own lazy `ensureCollection`s, so the DDL is v4's.
  await repos.chats.findByCharacterId(spec.characters[0].id);
  await repos.chats.getMessages('00000000-0000-4000-8000-000000000000');
  await repos.embeddingStatus.findByUserId(spec.users[0].id);
  await repos.backgroundJobs.findByUserId(spec.users[0].id, 'PENDING');
  await repos.vectorIndices.findMetaByCharacterId(spec.characters[0].id);
  await repos.groupCharacterMembers.findByCharacterId(spec.characters[0].id);
  await repos.memories.findByCharacterId(spec.characters[0].id);
  await repos.files.findByUserId(spec.users[0].id);

  closeMountIndexSQLiteClient();
  await closeDatabase();
  process.stderr.write(
    `built headshoulders fixture: main=${mainOut} mount=${mountOut} ` +
      `(${spec.users.length} users, ${spec.characters.length} characters)\n`,
  );
  process.exit(0);
}

main().catch((err) => {
  process.stderr.write(`headshoulders fixture build failed: ${err?.stack ?? err}\n`);
  process.exit(1);
});
