//! Generated byte-exact autonomous-room milestone/grace text (U4.1; v4
//! `lib/background-jobs/handlers/autonomous-room-turn.ts`, module-private
//! constants — extracted mechanically from the v4 SOURCE TEXT and evaluated
//! as JS, since v4 exports none of them). Do not hand-edit. Regenerate:
//!
//!   cd ~/source/quilltap-server
//!   npx tsx ~/source/quilltap-v5/harness/oracle/cases/gen-enclave-milestone-text.mjs \
//!     ~/source/quilltap-v5/crates/quilltap-core/src/enclave/milestones/milestone_text.rs
//!
//! `COMPOSED_MILESTONE_MESSAGES` holds every (binding × milestone) cell fully
//! composed by v4's OWN template literals — the no-drift check the Rust
//! composition in `super::build_milestone_message` is unit-tested against.

/// v4 `GRACE_CONTENT` (234 UTF-16 code units).
pub const GRACE_CONTENT: &str = r#"The Host rises with a rueful smile: we have, in candour, run past the allowance set aside for this gathering — yet it would be the height of rudeness to cut a guest off mid-thought. Let there be one last word, and then we shall close."#;

/// v4 `GRACE_OPAQUE` (173 UTF-16 code units).
pub const GRACE_OPAQUE: &str = r#"This conversation has reached its budget limit. You have one final turn to speak before it ends — say what most needs saying and bring the present scene to a graceful close."#;

// The milestone bit constants + thresholds as spelled in the v4 source; a unit
// test asserts the hand-documented constants in `super` equal these.
pub const SRC_MILESTONE_HALFWAY: i64 = 1;
pub const SRC_MILESTONE_NEAR_END: i64 = 2;
pub const SRC_MILESTONE_GRACE: i64 = 4;
pub const SRC_HALFWAY_THRESHOLD: f64 = 0.5;
pub const SRC_NEAR_END_THRESHOLD: f64 = 0.9;

/// v4 `MILESTONE_BINDING_PHRASE.time.hostHalf`.
pub const TIME_HOST_HALF: &str = r#"the time allotted to this gathering"#;
/// v4 `MILESTONE_BINDING_PHRASE.time.hostEnd`.
pub const TIME_HOST_END: &str = r#"our time together"#;
/// v4 `MILESTONE_BINDING_PHRASE.time.opaqueNoun`.
pub const TIME_OPAQUE_NOUN: &str = r#"allotted time"#;
/// v4 `MILESTONE_BINDING_PHRASE.time.pauses`.
pub const TIME_PAUSES: bool = false;

/// v4 `MILESTONE_BINDING_PHRASE.turns.hostHalf`.
pub const TURNS_HOST_HALF: &str = r#"the exchanges allotted to this gathering"#;
/// v4 `MILESTONE_BINDING_PHRASE.turns.hostEnd`.
pub const TURNS_HOST_END: &str = r#"the exchanges allotted to us"#;
/// v4 `MILESTONE_BINDING_PHRASE.turns.opaqueNoun`.
pub const TURNS_OPAQUE_NOUN: &str = r#"allotted exchanges"#;
/// v4 `MILESTONE_BINDING_PHRASE.turns.pauses`.
pub const TURNS_PAUSES: bool = false;

/// v4 `MILESTONE_BINDING_PHRASE.tokens.hostHalf`.
pub const TOKENS_HOST_HALF: &str = r#"the allowance set aside for this gathering"#;
/// v4 `MILESTONE_BINDING_PHRASE.tokens.hostEnd`.
pub const TOKENS_HOST_END: &str = r#"the gathering's allowance"#;
/// v4 `MILESTONE_BINDING_PHRASE.tokens.opaqueNoun`.
pub const TOKENS_OPAQUE_NOUN: &str = r#"allotted length"#;
/// v4 `MILESTONE_BINDING_PHRASE.tokens.pauses`.
pub const TOKENS_PAUSES: bool = false;

/// v4 `MILESTONE_BINDING_PHRASE.daily.hostHalf`.
pub const DAILY_HOST_HALF: &str = r#"the day's shared allowance"#;
/// v4 `MILESTONE_BINDING_PHRASE.daily.hostEnd`.
pub const DAILY_HOST_END: &str = r#"the day's allowance"#;
/// v4 `MILESTONE_BINDING_PHRASE.daily.opaqueNoun`.
pub const DAILY_OPAQUE_NOUN: &str = r#"allowance for the day"#;
/// v4 `MILESTONE_BINDING_PHRASE.daily.pauses`.
pub const DAILY_PAUSES: bool = true;

/// Every fully-composed (binding, milestone, systemKind, content,
/// opaqueContent) cell, evaluated from v4's own `buildMilestoneMessage`
/// template literals by the generator.
pub const COMPOSED_MILESTONE_MESSAGES: &[(&str, &str, &str, &str, &str)] = &[
    (
        "time",
        "halfway",
        "autonomous-room-halfway",
        r#"The Host raps a crystal glass for attention: we have reached the midpoint of the time allotted to this gathering. There is room yet — but let the conversation begin to find its way toward what matters most."#,
        r#"This conversation is halfway through its allotted time. Continue naturally, but begin steering toward what matters most before it ends."#,
    ),
    (
        "time",
        "near-end",
        "autonomous-room-nearing-end",
        r#"The Host consults a pocket-watch and clears their throat: our time together is nearly spent, and this gathering must soon draw to a close. Say now what most needs saying, and bring your threads to a graceful rest."#,
        r#"This conversation is almost out of its allotted time and will end soon. Say what most needs to be said, and begin bringing the scene to a close."#,
    ),
    (
        "turns",
        "halfway",
        "autonomous-room-halfway",
        r#"The Host raps a crystal glass for attention: we have reached the midpoint of the exchanges allotted to this gathering. There is room yet — but let the conversation begin to find its way toward what matters most."#,
        r#"This conversation is halfway through its allotted exchanges. Continue naturally, but begin steering toward what matters most before it ends."#,
    ),
    (
        "turns",
        "near-end",
        "autonomous-room-nearing-end",
        r#"The Host consults a pocket-watch and clears their throat: the exchanges allotted to us is nearly spent, and this gathering must soon draw to a close. Say now what most needs saying, and bring your threads to a graceful rest."#,
        r#"This conversation is almost out of its allotted exchanges and will end soon. Say what most needs to be said, and begin bringing the scene to a close."#,
    ),
    (
        "tokens",
        "halfway",
        "autonomous-room-halfway",
        r#"The Host raps a crystal glass for attention: we have reached the midpoint of the allowance set aside for this gathering. There is room yet — but let the conversation begin to find its way toward what matters most."#,
        r#"This conversation is halfway through its allotted length. Continue naturally, but begin steering toward what matters most before it ends."#,
    ),
    (
        "tokens",
        "near-end",
        "autonomous-room-nearing-end",
        r#"The Host consults a pocket-watch and clears their throat: the gathering's allowance is nearly spent, and this gathering must soon draw to a close. Say now what most needs saying, and bring your threads to a graceful rest."#,
        r#"This conversation is almost out of its allotted length and will end soon. Say what most needs to be said, and begin bringing the scene to a close."#,
    ),
    (
        "daily",
        "halfway",
        "autonomous-room-halfway",
        r#"The Host raps a crystal glass for attention: we have reached the midpoint of the day's shared allowance. There is room yet — but let the conversation begin to find its way toward what matters most."#,
        r#"This conversation is halfway through its allowance for the day. Continue naturally, but begin steering toward what matters most before it pauses."#,
    ),
    (
        "daily",
        "near-end",
        "autonomous-room-nearing-end",
        r#"The Host consults a pocket-watch and clears their throat: the day's allowance is nearly spent, and this gathering must soon pause for the day. Finish now what most needs saying — the company shall reconvene when the allowance comes round again."#,
        r#"This conversation is almost out of its allowance for the day and will pause shortly — it will resume later, but not before stopping for now. Say what most needs to be said, and bring the present scene to a close."#,
    ),
];
