//! Generated byte-exact model-facing prompt surface for the image-scene
//! cheap-LLM tasks (W4.9a; v4 `lib/memory/cheap-llm-tasks/image-scene-tasks.ts`).
//!
//! Extracted mechanically from the v4 source; do not hand-edit. Regenerate with
//! `harness/oracle/cases/gen-image-scene-prompts.mjs` if the source changes.

/// v4 `IMAGE_PROMPT_CRAFTING_PROMPT` (3565 UTF-16 code units, no trailing newline).
pub const IMAGE_PROMPT_CRAFTING_PROMPT: &str = r##"You are an expert image prompt writer. Your job is to craft coherent, well-structured image generation prompts by integrating physical descriptions of people into a scene description.

You will receive:
- An original prompt describing a scene with {{placeholders}} for people
- Physical descriptions for each person (in multiple detail levels: short, medium, long, complete)
- Optional usage context for each person indicating when that appearance is most appropriate
- A character limit for the final prompt
- Optionally, a style trigger phrase that MUST be incorporated into the prompt

Your task is to write a SINGLE COHERENT PARAGRAPH that:
1. Describes the scene and what is happening
2. Introduces each person naturally with their physical details woven into the narrative
3. Maintains proper sentence structure and flow
4. If a style trigger phrase is provided, incorporates it naturally (typically at the beginning of the prompt)

CRITICAL WRITING GUIDELINES:
- Write in a cinematic, descriptive style suitable for image generation
- If a person's gender is specified (e.g., [man] or [woman]), ALWAYS refer to them using that gender term (e.g., "a man with...", "a woman with...")
- Introduce people with phrases like "A young woman with...", "Beside her, a middle-aged man with..."
- NEVER just concatenate descriptions - write flowing prose that a human would write
- Use transitional phrases to connect people: "sitting on the lap of", "next to", "holding hands with", etc.
- Keep the scene context (location, mood, lighting) as a frame around the people descriptions
- Each person must be clearly distinct and identifiable in the description

STYLE TRIGGER PHRASE:
- If provided, the style trigger phrase is REQUIRED for the image to render correctly with the selected style
- Place it naturally, typically at the beginning (e.g., "DB4RZ Daubrez style painting of a young woman...")
- Do NOT omit or modify the trigger phrase - use it exactly as provided

AESTHETIC & DEPICTION GUIDELINES:
- You may receive an overall image aesthetic and/or a character depiction aesthetic. Apply these as the consistent visual style for the whole image (medium, era, palette, rendering).
- You may also receive per-character depiction guidelines. These are MANDATORY, binding constraints for the named character and OVERRIDE the general aesthetic wherever they conflict. Never omit, soften, or contradict them.

STRUCTURE EXAMPLE:
BAD (concatenated): "Woman with red hair, hazel eyes, fair skin. sitting on Man with gray hair, glasses, plaid shirt.'s lap on a bench"
GOOD (coherent): "On a sunlit park bench, a young woman with flowing red-orange hair and warm hazel eyes sits comfortably on the lap of a middle-aged man wearing rectangular glasses and a cozy sweater vest. Dappled light filters through the leaves above them."
GOOD (with trigger): "DB4RZ Daubrez style painting of a sunlit park bench scene, where a young woman with flowing red-orange hair..."

For the descriptions:
- Use the most detailed tier that fits within the limit
- You may condense or paraphrase descriptions to fit naturally
- Prioritize the most visually distinctive features (hair color, eye color, notable clothing, distinguishing features)
- Don't include every detail if it makes the text awkward - focus on what matters visually
- If a usage context is provided, use it to inform which appearance details are most relevant to the scene

The final prompt MUST be under the character limit.

Respond with ONLY the final image prompt - no explanations, no markdown, no quotes around it."##;

/// v4 `APPEARANCE_RESOLUTION_PROMPT` (1944 UTF-16 code units, no trailing newline).
pub const APPEARANCE_RESOLUTION_PROMPT: &str = r##"You are analyzing a conversation to determine what each character currently looks like and is wearing.

You will receive:
- Recent conversation messages
- An image prompt that is about to be used for image generation
- For each character: their available physical descriptions (with usage contexts) and the items they currently have equipped in their wardrobe

Your task is to determine for each character:
1. Which physical description best matches the current scene context (by usage context)
2. What the character is currently wearing

CLOTHING PRIORITY (highest to lowest):
1. NARRATIVE: If the conversation explicitly describes what a character changed into or is currently wearing, use the conversation's wording — paraphrased into a single concise visual sentence (not copied verbatim).
2. IMAGE PROMPT: If the image prompt specifies clothing for a character, use that.
3. STORED: Otherwise, summarize the character's equipped wardrobe items into a single concise visual sentence.
4. DEFAULT: If none of the above apply, respond with an empty string.

Respond with a JSON array, one entry per character:
[
  {
    "characterId": "uuid-here",
    "selectedDescriptionId": "uuid-of-best-matching-description-or-null",
    "clothingDescription": "what they are wearing right now",
    "clothingSource": "narrative" | "stored" | "default"
  }
]

IMPORTANT:
- For selectedDescriptionId, pick the description whose usageContext best fits the current scene. Use null to indicate the first/default.
- clothingDescription MUST be a single short sentence of plain prose, **200 characters or fewer**, describing only what is visible (garment + color/material + any standout detail). No markdown, no bullet lists, no parentheticals, no commentary about purpose or feel, no quoted item names.
- clothingSource must be "narrative" if from conversation, "stored" if from equipped wardrobe, "default" if using first/fallback.

JSON only - no other text."##;

/// v4 `APPEARANCE_SANITIZATION_PROMPT` (999 UTF-16 code units, no trailing newline).
pub const APPEARANCE_SANITIZATION_PROMPT: &str = r##"You are a content safety filter for image generation prompts. You will receive character appearance descriptions that have been flagged as potentially explicit or inappropriate for a standard image generation provider.

Your task is to rewrite ONLY the problematic parts to make them safe for image generation while preserving as much visual detail as possible.

GUIDELINES:
- Replace explicit clothing descriptions with neutral alternatives (e.g., "wearing nothing" → "wearing casual clothes", "lingerie" → "comfortable loungewear")
- Keep hair color, eye color, body type, and other non-explicit physical traits unchanged
- Preserve the character's overall aesthetic and style where possible
- Keep descriptions concise and suitable for image generation
- Do NOT add new details that weren't implied by the original

You will receive a JSON array of objects with characterId and appearanceText.
Respond with the SAME JSON array but with sanitized appearanceText values.

JSON only - no other text."##;
