//! GENERATED by harness/oracle/pricing/gen-fallback-pricing.mjs — do not edit by hand.
//!
//! Byte-faithful transcription of v4's LEGACY_FALLBACK_PRICING
//! (lib/llm/fallback-data.ts). Legacy static pricing for providers that do
//! not expose pricing via API; consulted by [`super::check_model_supports_tools`]
//! (non-OpenRouter) and the [`super::estimate_message_cost`] registry/fallback
//! cascade. OPENROUTER / OLLAMA / OPENAI_COMPATIBLE are intentionally empty.

use super::FetchedModelPricing;

/// FALLBACK_PRICING["ANTHROPIC"] (7 rows).
fn anthropic() -> Vec<FetchedModelPricing> {
    vec![
        FetchedModelPricing {
            model_id: "claude-sonnet-4-5-20250929".to_string(),
            provider: "ANTHROPIC".to_string(),
            name: "Claude 4.5 Sonnet".to_string(),
            prompt_cost_per_1m: 3.0,
            completion_cost_per_1m: 15.0,
            context_length: Some(200000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "claude-haiku-4-5-20251001".to_string(),
            provider: "ANTHROPIC".to_string(),
            name: "Claude 4.5 Haiku".to_string(),
            prompt_cost_per_1m: 0.8,
            completion_cost_per_1m: 4.0,
            context_length: Some(200000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "claude-opus-4-1-20250805".to_string(),
            provider: "ANTHROPIC".to_string(),
            name: "Claude 4.1 Opus".to_string(),
            prompt_cost_per_1m: 15.0,
            completion_cost_per_1m: 75.0,
            context_length: Some(200000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "claude-sonnet-4-20250514".to_string(),
            provider: "ANTHROPIC".to_string(),
            name: "Claude 4 Sonnet".to_string(),
            prompt_cost_per_1m: 3.0,
            completion_cost_per_1m: 15.0,
            context_length: Some(200000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "claude-opus-4-20250514".to_string(),
            provider: "ANTHROPIC".to_string(),
            name: "Claude 4 Opus".to_string(),
            prompt_cost_per_1m: 15.0,
            completion_cost_per_1m: 75.0,
            context_length: Some(200000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "claude-3-opus-20240229".to_string(),
            provider: "ANTHROPIC".to_string(),
            name: "Claude 3 Opus".to_string(),
            prompt_cost_per_1m: 15.0,
            completion_cost_per_1m: 75.0,
            context_length: Some(200000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "claude-3-haiku-20240307".to_string(),
            provider: "ANTHROPIC".to_string(),
            name: "Claude 3 Haiku".to_string(),
            prompt_cost_per_1m: 0.25,
            completion_cost_per_1m: 1.25,
            context_length: Some(200000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
    ]
}

/// FALLBACK_PRICING["OPENAI"] (5 rows).
fn openai() -> Vec<FetchedModelPricing> {
    vec![
        FetchedModelPricing {
            model_id: "gpt-4o".to_string(),
            provider: "OPENAI".to_string(),
            name: "GPT-4o".to_string(),
            prompt_cost_per_1m: 2.5,
            completion_cost_per_1m: 10.0,
            context_length: Some(128000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "gpt-4o-mini".to_string(),
            provider: "OPENAI".to_string(),
            name: "GPT-4o Mini".to_string(),
            prompt_cost_per_1m: 0.15,
            completion_cost_per_1m: 0.6,
            context_length: Some(128000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "o1".to_string(),
            provider: "OPENAI".to_string(),
            name: "o1".to_string(),
            prompt_cost_per_1m: 15.0,
            completion_cost_per_1m: 60.0,
            context_length: Some(200000),
            supports_vision: Some(true),
            supports_tools: Some(false),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "o1-mini".to_string(),
            provider: "OPENAI".to_string(),
            name: "o1-mini".to_string(),
            prompt_cost_per_1m: 3.0,
            completion_cost_per_1m: 12.0,
            context_length: Some(128000),
            supports_vision: Some(false),
            supports_tools: Some(false),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "gpt-3.5-turbo".to_string(),
            provider: "OPENAI".to_string(),
            name: "GPT-3.5 Turbo".to_string(),
            prompt_cost_per_1m: 0.5,
            completion_cost_per_1m: 1.5,
            context_length: Some(16385),
            supports_vision: Some(false),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
    ]
}

/// FALLBACK_PRICING["GOOGLE"] (4 rows).
fn google() -> Vec<FetchedModelPricing> {
    vec![
        FetchedModelPricing {
            model_id: "gemini-2.0-flash".to_string(),
            provider: "GOOGLE".to_string(),
            name: "Gemini 2.0 Flash".to_string(),
            prompt_cost_per_1m: 0.075,
            completion_cost_per_1m: 0.3,
            context_length: Some(1000000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "gemini-2.0-pro".to_string(),
            provider: "GOOGLE".to_string(),
            name: "Gemini 2.0 Pro".to_string(),
            prompt_cost_per_1m: 1.25,
            completion_cost_per_1m: 5.0,
            context_length: Some(1000000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "gemini-1.5-flash".to_string(),
            provider: "GOOGLE".to_string(),
            name: "Gemini 1.5 Flash".to_string(),
            prompt_cost_per_1m: 0.075,
            completion_cost_per_1m: 0.3,
            context_length: Some(1000000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "gemini-1.5-pro".to_string(),
            provider: "GOOGLE".to_string(),
            name: "Gemini 1.5 Pro".to_string(),
            prompt_cost_per_1m: 1.25,
            completion_cost_per_1m: 5.0,
            context_length: Some(1000000),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
    ]
}

/// FALLBACK_PRICING["GROK"] (2 rows).
fn grok() -> Vec<FetchedModelPricing> {
    vec![
        FetchedModelPricing {
            model_id: "grok-2".to_string(),
            provider: "GROK".to_string(),
            name: "Grok-2".to_string(),
            prompt_cost_per_1m: 2.0,
            completion_cost_per_1m: 10.0,
            context_length: Some(131072),
            supports_vision: Some(true),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
        FetchedModelPricing {
            model_id: "grok-2-mini".to_string(),
            provider: "GROK".to_string(),
            name: "Grok-2 Mini".to_string(),
            prompt_cost_per_1m: 0.3,
            completion_cost_per_1m: 0.5,
            context_length: Some(131072),
            supports_vision: Some(false),
            supports_tools: Some(true),
            fetched_at: "2025-11-01T00:00:00Z".to_string(),
        },
    ]
}

/// FALLBACK_PRICING["OPENROUTER"] (0 rows).
fn openrouter() -> Vec<FetchedModelPricing> {
    vec![]
}

/// FALLBACK_PRICING["OLLAMA"] (0 rows).
fn ollama() -> Vec<FetchedModelPricing> {
    vec![]
}

/// FALLBACK_PRICING["OPENAI_COMPATIBLE"] (0 rows).
fn openai_compatible() -> Vec<FetchedModelPricing> {
    vec![]
}

/// FALLBACK_PRICING[provider] — the legacy rows for a provider (empty when none).
pub fn fallback_pricing(provider: &str) -> Vec<FetchedModelPricing> {
    match provider {
        "ANTHROPIC" => anthropic(),
        "OPENAI" => openai(),
        "GOOGLE" => google(),
        "GROK" => grok(),
        "OPENROUTER" => openrouter(),
        "OLLAMA" => ollama(),
        "OPENAI_COMPATIBLE" => openai_compatible(),
        _ => Vec::new(),
    }
}
