/**
 * `help-categories.ts` parity — v4 `lib/help-guide/categories.ts` at `d883a5ee1`.
 *
 * Two independent proofs, because either alone is weak:
 *
 *  1. **Byte identity of the transcribed tables** against a capture of v4's REAL
 *     module (`__fixtures__/help-guide-tables.json`). A hand-transcribed 68-slug
 *     table is exactly the kind of thing inspection misses a row of.
 *  2. **A recorded-vector corpus** — 32 URLs run through v4's real
 *     `getCategoryForUrl` — plus v4's own 187-line jest suite
 *     (`__tests__/unit/lib/help-guide/categories.test.ts`) ported case-for-case.
 *     The suite states the intent; the corpus pins the edges the suite never
 *     asks about (`/settingsish`, `/?tab=system`, `/settings?tab=`).
 *
 * Expected values were generated by RUNNING v4's code at the pin, never read off
 * it — `npx jest --watchman=false __tests__/unit/lib/help-guide/categories.test.ts`
 * green at `d883a5ee1`, and `__fixtures__/capture-v4-help.test.tsx` for the JSON.
 */

import { describe, expect, it } from 'vitest';

import {
  EXCLUDED_DOCUMENTS,
  HELP_CATEGORIES,
  URL_CATEGORY_MAP,
  getCategoryForUrl,
  mostSpecificMatch,
} from './help-categories';
import tables from './__fixtures__/help-guide-tables.json';
import vectors from './__fixtures__/help-guide-vectors.json';

describe('help-categories — byte identity against the v4 capture', () => {
  it('HELP_CATEGORIES matches v4 row for row, slug for slug', () => {
    expect(JSON.parse(JSON.stringify(HELP_CATEGORIES))).toEqual(tables.HELP_CATEGORIES);
  });

  it('URL_CATEGORY_MAP matches v4 in content AND ORDER', () => {
    // Order is load-bearing twice over: `filter` walks it, and the
    // longest-pattern reduce breaks ties by FIRST-seen on equal length.
    expect(JSON.parse(JSON.stringify(URL_CATEGORY_MAP))).toEqual(tables.URL_CATEGORY_MAP);
  });

  it('EXCLUDED_DOCUMENTS matches v4', () => {
    expect(JSON.parse(JSON.stringify(EXCLUDED_DOCUMENTS))).toEqual(tables.EXCLUDED_DOCUMENTS);
  });

  it('carries the dangling `shell-tools` slug v4 has (a reproduced quirk, not a bug)', () => {
    // v4's `chats` category names a slug with no document. The Guide silently
    // omits it because topics resolve through the loaded document map. Pinned so
    // a well-meaning "cleanup" of the table shows up as a red spec.
    const chats = HELP_CATEGORIES.find((c) => c.id === 'chats');
    expect(chats?.documents).toContain('shell-tools');
  });
});

describe('getCategoryForUrl — the recorded-vector corpus (from v4 itself)', () => {
  it('covers at least 20 URLs', () => {
    expect(vectors.getCategoryForUrl.length).toBeGreaterThanOrEqual(20);
  });

  for (const row of vectors.getCategoryForUrl) {
    it(`${JSON.stringify(row.url)} → ${row.categoryId}`, () => {
      expect(getCategoryForUrl(row.url)).toBe(row.categoryId);
    });
  }
});

// ---------------------------------------------------------------------------
// v4's own suite, ported case-for-case (`categories.test.ts`).
// ---------------------------------------------------------------------------

describe('Help Guide Categories', () => {
  describe('HELP_CATEGORIES', () => {
    it('should have 11 categories', () => {
      expect(HELP_CATEGORIES).toHaveLength(11);
    });

    it('should have unique category IDs', () => {
      const ids = HELP_CATEGORIES.map((c) => c.id);
      expect(new Set(ids).size).toBe(ids.length);
    });

    it('should have non-empty documents array for every category', () => {
      for (const category of HELP_CATEGORIES) {
        expect(category.documents.length).toBeGreaterThan(0);
      }
    });

    it('should have id, label, and documents on every category', () => {
      for (const category of HELP_CATEGORIES) {
        expect(typeof category.id).toBe('string');
        expect(typeof category.label).toBe('string');
        expect(Array.isArray(category.documents)).toBe(true);
      }
    });

    it('should include expected category IDs', () => {
      const ids = HELP_CATEGORIES.map((c) => c.id);
      expect(ids).toContain('getting-started');
      expect(ids).toContain('characters');
      expect(ids).toContain('chats');
      expect(ids).toContain('projects');
      expect(ids).toContain('files');
      expect(ids).toContain('memory-search');
      expect(ids).toContain('ai-providers');
      expect(ids).toContain('appearance');
      expect(ids).toContain('settings-system');
      expect(ids).toContain('account');
      expect(ids).toContain('content-routing');
    });
  });

  describe('EXCLUDED_DOCUMENTS', () => {
    it('should contain help-chat', () => {
      expect(EXCLUDED_DOCUMENTS).toContain('help-chat');
    });
  });

  describe('getCategoryForUrl', () => {
    it('should return getting-started for exact /', () => {
      expect(getCategoryForUrl('/')).toBe('getting-started');
    });

    it('should not match root for other paths', () => {
      expect(getCategoryForUrl('/something')).toBeNull();
    });

    it('should return characters for /aurora', () => {
      expect(getCategoryForUrl('/aurora')).toBe('characters');
    });

    it('should return characters for /aurora/123/edit (prefix matching)', () => {
      expect(getCategoryForUrl('/aurora/123/edit')).toBe('characters');
    });

    it('should return chats for /salon', () => {
      expect(getCategoryForUrl('/salon')).toBe('chats');
    });

    it('should return projects for /prospero', () => {
      expect(getCategoryForUrl('/prospero')).toBe('projects');
    });

    it('should return files for /files', () => {
      expect(getCategoryForUrl('/files')).toBe('files');
    });

    it('should return account for /profile', () => {
      expect(getCategoryForUrl('/profile')).toBe('account');
    });

    it('should return getting-started for /setup', () => {
      expect(getCategoryForUrl('/setup')).toBe('getting-started');
    });

    it('should return settings-system for /settings (no tab)', () => {
      expect(getCategoryForUrl('/settings')).toBe('settings-system');
    });

    it('should return settings-system for /settings?tab=system', () => {
      expect(getCategoryForUrl('/settings?tab=system')).toBe('settings-system');
    });

    it('should return settings-system for /settings?tab=templates', () => {
      expect(getCategoryForUrl('/settings?tab=templates')).toBe('settings-system');
    });

    it('should return content-routing for /settings?tab=images', () => {
      expect(getCategoryForUrl('/settings?tab=images')).toBe('content-routing');
    });

    it('should return memory-search for /settings?tab=memory', () => {
      expect(getCategoryForUrl('/settings?tab=memory')).toBe('memory-search');
    });

    it('should return appearance for /settings?tab=appearance', () => {
      expect(getCategoryForUrl('/settings?tab=appearance')).toBe('appearance');
    });

    it('should return chats for /settings?tab=chat', () => {
      expect(getCategoryForUrl('/settings?tab=chat')).toBe('chats');
    });

    it('should return ai-providers for /settings?tab=providers', () => {
      expect(getCategoryForUrl('/settings?tab=providers')).toBe('ai-providers');
    });

    it('should pick the most specific match (tab param over bare path)', () => {
      expect(getCategoryForUrl('/settings?tab=system')).toBe('settings-system');
      expect(getCategoryForUrl('/settings?tab=images')).toBe('content-routing');
    });

    it('should match with extra query params', () => {
      expect(getCategoryForUrl('/settings?tab=system&foo=bar')).toBe('settings-system');
    });

    it('should return null for unknown URL', () => {
      expect(getCategoryForUrl('/unknown-page')).toBeNull();
    });

    it('should return null for empty string', () => {
      expect(getCategoryForUrl('')).toBeNull();
    });

    it('should fall back to settings-system for unknown tab', () => {
      expect(getCategoryForUrl('/settings?tab=unknown')).toBe('settings-system');
    });
  });

  describe('URL_CATEGORY_MAP', () => {
    it('should have entries for all major routes', () => {
      const patterns = URL_CATEGORY_MAP.map((e) => e.pattern);
      expect(patterns).toContain('/');
      expect(patterns).toContain('/aurora');
      expect(patterns).toContain('/salon');
      expect(patterns).toContain('/prospero');
      expect(patterns).toContain('/files');
      expect(patterns).toContain('/profile');
      expect(patterns).toContain('/settings');
      expect(patterns).toContain('/setup');
    });

    it('should reference only valid category IDs', () => {
      const validIds = new Set(HELP_CATEGORIES.map((c) => c.id));
      for (const entry of URL_CATEGORY_MAP) {
        expect(validIds.has(entry.categoryId)).toBe(true);
      }
    });
  });
});

describe('mostSpecificMatch — the longest-pattern tie-break', () => {
  // Against the real URL_CATEGORY_MAP this rule is INVISIBLE: the table lists
  // the seven `?tab=` rows before bare `/settings`, so first-wins and
  // longest-wins agree on every url in the corpus (measured — a mutation
  // collapsing the reduce to `prev` survives all 32 vectors). These two cases
  // are what give the rule a discriminator.
  it('picks the longest pattern even when it is not first', () => {
    const reversed = [{ pattern: '/settings' }, { pattern: '/settings?tab=images' }];
    expect(mostSpecificMatch(reversed).pattern).toBe('/settings?tab=images');
  });

  it('keeps the FIRST of two equal-length patterns (reduce semantics)', () => {
    const tie = [{ pattern: '/aaa', id: 1 }, { pattern: '/bbb', id: 2 }];
    expect(mostSpecificMatch(tie).id).toBe(1);
  });
});
