import { formatCostForDisplay, formatTokenCount } from './format-tokens';

/**
 * The expectation tables below are not hand-written: they were GENERATED by
 * driving v4's real `lib/utils/format-tokens.ts` over this corpus
 * (`npx tsx` from the `~/source/quilltap-server` checkout @ `02865bdb`) and
 * pinned verbatim. That makes this the tier-1 equivalence proof for the leaf —
 * every string here is v4's own output, not a guess at it.
 *
 * The corpus deliberately straddles every band edge, because the interesting
 * behavior is all at the boundaries.
 */
describe('format-tokens (v4 lib/utils/format-tokens.ts)', () => {
  describe('formatCostForDisplay', () => {
    const cases: [number | null, string][] = [
      [null, 'N/A'],
      [0, 'Free'],
      // A non-zero cost too small to survive 4 digits still renders as "$0.0000"
      // — NOT "Free". v4 checks `=== 0` before rounding, so the distinction
      // between "no cost" and "rounds to no cost" is preserved on purpose.
      [1e-7, '$0.0000'],
      [0.0001, '$0.0001'],
      [0.0023, '$0.0023'],
      [0.005, '$0.0050'],
      // Below the 0.01 band edge, so 4 digits — which then round UP to display
      // a value that looks like it belongs in the next band.
      [0.00999, '$0.0100'],
      [0.00995, '$0.0100'],
      [0.01, '$0.010'],
      [0.0105, '$0.011'],
      [0.1234, '$0.123'],
      [0.999, '$0.999'],
      // Same shape at the $1 edge: still the sub-$1 band (3 digits), rounded up
      // to "$1.000".
      [0.9999, '$1.000'],
      [1, '$1.00'],
      [1.005, '$1.00'],
      [1.5, '$1.50'],
      [12.345, '$12.35'],
      [999.999, '$1000.00'],
      [1000, '$1000.00'],
    ];

    for (const [input, expected] of cases) {
      it(`formats ${JSON.stringify(input)} as ${expected}`, () => {
        expect(formatCostForDisplay(input)).toBe(expected);
      });
    }
  });

  describe('formatTokenCount', () => {
    const cases: [number, string][] = [
      [0, '0'],
      [1, '1'],
      [9, '9'],
      [42, '42'],
      [999, '999'],
      [1000, '1.0K'],
      [1049, '1.0K'],
      [1050, '1.1K'],
      [1500, '1.5K'],
      [1999, '2.0K'],
      [9999, '10.0K'],
      // v4 bands on the RAW value, not the rounded one: 999_999 is under the 1M
      // threshold, so it renders "1000.0K" rather than "1.0M".
      [999950, '1000.0K'],
      [999999, '1000.0K'],
      [1000000, '1.0M'],
      [1049999, '1.0M'],
      [2300000, '2.3M'],
      [2350000, '2.4M'],
      [12345678, '12.3M'],
    ];

    for (const [input, expected] of cases) {
      it(`formats ${input} as ${expected}`, () => {
        expect(formatTokenCount(input)).toBe(expected);
      });
    }
  });
});
