/**
 * The chipLabel + side-effects arms of the browser schema twin (v4
 * `c4d4b0de`, "custom-tool chip labels, two-block bubbles, and side effects"),
 * pinned against v4's REAL Zod at that commit (P4.D36 unit 2).
 *
 * The committed corpus NDJSON is P4.D35's to regenerate (§C of the round's
 * shared contract), so this file is the stand-in with identical rigour — the
 * same shape `custom-tool-types.state.spec.ts`, `.llm.spec.ts` and
 * `.gate.spec.ts` use. Every row below was CAPTURED by driving v4's own
 * `QtapCustomToolSchema.safeParse` + `formatDefinitionIssues` +
 * `collectUnknownKeys` over the input bytes, and is byte-compared here exactly
 * as the corpus spec compares the corpus: the verdict, the parsed data (via
 * `JSON.stringify`, so key ORDER is pinned — `chipLabel` lands between `title`
 * and `description`, `effects` between `llm` and `outcomes`, whatever order
 * the file wrote them in), the unknown-key report, and the FULL rejection
 * sentence.
 *
 * Regen recipe (the capture script is scratch, the ROWS are the artifact):
 *
 * ```ts
 * // in ~/source/quilltap-server @ c4d4b0de, `npx tsx <script>` with Node 24:
 * import { QtapCustomToolSchema, formatDefinitionIssues, collectUnknownKeys,
 *          parseEffectTarget } from '@/lib/pascal/custom-tool.types'
 * const r = QtapCustomToolSchema.safeParse(JSON.parse(inputJson))
 * ({ success: r.success,
 *    reason: r.success ? null : formatDefinitionIssues(r.error),
 *    data: r.success ? JSON.stringify(r.data) : null,
 *    unknownKeys: collectUnknownKeys(JSON.parse(inputJson)) })
 * ```
 *
 * v4 anchors: `lib/pascal/custom-tool.types.ts` — `EffectWhenSchema`,
 * `CustomToolEffectSchema`, `parseEffectTarget`, the `chipLabel` key,
 * `validateWhenSubjects` (the shared walk outcome rows now share with effect
 * conditions), and `validateEffects`.
 *
 * Three behaviours worth naming, all empirical rather than inferred:
 *
 *  - an empty `target` collects BOTH sentences — Zod's `Too small` (a check, so
 *    continuable) and then `target must start with "state." or "metadata."`
 *    from the superRefine, which still runs because nothing aborted. The same
 *    doubling happens for an empty or over-long `value`.
 *  - `effects: at most 16 effects` fires ALONGSIDE per-effect superRefine
 *    complaints, because a bad target is not a schema-shape failure: the array
 *    check is only skipped when an ELEMENT aborts.
 *  - the `value` union reports all three branch failures joined by ` — or — `
 *    for a null/object/array value, but an EMPTY string hoists the string
 *    branch's own `Too small` alone (exactly one non-aborted branch).
 */

import { describe, expect, it } from 'vitest';

import {
  collectUnknownKeys,
  formatDefinitionIssues,
  parseEffectTarget,
  safeParse,
} from './custom-tool-types';

/** One captured `QtapCustomToolSchema.safeParse` verdict. */
interface DefinitionRow {
  kind: 'definition';
  id: string;
  /** The definition's BYTES — never a re-stringified structure. */
  inputJson: string;
  success: boolean;
  reason: string | null;
  data: string | null;
  unknownKeys: string[];
}

/** One captured `parseEffectTarget` verdict. */
interface TargetRow {
  kind: 'target';
  id: string;
  target: string;
  ok: boolean;
  /** The parsed target, SERIALIZED, so `path` order and element types are pinned. */
  parsed: string | null;
  reason: string | null;
}

type Row = DefinitionRow | TargetRow;

const CAPTURED: readonly Row[] = [
  {"kind": "definition", "id": "chip-label-templated", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"chipLabel\":\"Agent lambda — {{params.label}}\"}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"chipLabel\":\"Agent lambda — {{params.label}}\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "chip-label-at-cap", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"chipLabel\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"chipLabel\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "chip-label-empty", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"chipLabel\":\"\"}", "success": false, "reason": "chipLabel: Too small: expected string to have >=1 characters", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "chip-label-over-cap", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"chipLabel\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}", "success": false, "reason": "chipLabel: Too big: expected string to have <=160 characters", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "chip-label-not-a-string", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"chipLabel\":42}", "success": false, "reason": "chipLabel: Invalid input: expected string, received number", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "chip-label-unknown-placeholder", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"chipLabel\":\"{{params.never_declared}}\"}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"chipLabel\":\"{{params.never_declared}}\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "chip-label-with-title", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"title\":\"Probe the Thing\",\"chipLabel\":\"Probe — {{value}}\"}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"title\":\"Probe the Thing\",\"chipLabel\":\"Probe — {{value}}\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-literal-number", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.encounter.count\",\"value\":3}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"state.encounter.count\",\"value\":3}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-literal-boolean", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"metadata.lockBroken\",\"value\":true}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"metadata.lockBroken\",\"value\":true}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-quoted-prose", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"metadata.lockpick\",\"value\":\"'broken pick'\"}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"metadata.lockpick\",\"value\":\"'broken pick'\"}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-expression-over-subjects", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"parameters\":{\"scale\":{\"type\":\"number\",\"default\":1}},\"effects\":[{\"target\":\"state.tally\",\"value\":\"{{state.tally}} + {{params.scale}}\"}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"parameters\":{\"scale\":{\"type\":\"number\",\"default\":1}},\"effects\":[{\"target\":\"state.tally\",\"value\":\"{{state.tally}} + {{params.scale}}\"}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-outcome-eq", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"outcome\":{\"eq\":\"success\"}},\"target\":\"state.wins\",\"value\":1}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"when\":{\"outcome\":{\"eq\":\"success\"}},\"target\":\"state.wins\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-outcome-neq", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"outcome\":{\"neq\":\"failure\"}},\"target\":\"state.wins\",\"value\":1}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"when\":{\"outcome\":{\"neq\":\"failure\"}},\"target\":\"state.wins\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-outcome-both", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"outcome\":{\"eq\":\"success\",\"neq\":\"failure\"}},\"target\":\"state.wins\",\"value\":1}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"when\":{\"outcome\":{\"eq\":\"success\",\"neq\":\"failure\"}},\"target\":\"state.wins\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-metadata", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"metadata\":{\"hasKey\":{\"eq\":true}}},\"target\":\"state.opened\",\"value\":true}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"when\":{\"metadata\":{\"hasKey\":{\"eq\":true}}},\"target\":\"state.opened\",\"value\":true}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-value-and-outcome", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"gt\":0.5,\"outcome\":{\"neq\":\"failure\"}},\"target\":\"state.x\",\"value\":1}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"when\":{\"gt\":0.5,\"outcome\":{\"neq\":\"failure\"}},\"target\":\"state.x\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-roll", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"roll\":{\"gte\":15}},\"target\":\"state.x\",\"value\":1}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"when\":{\"roll\":{\"gte\":15}},\"target\":\"state.x\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-params", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"parameters\":{\"scale\":{\"type\":\"number\",\"default\":1}},\"effects\":[{\"when\":{\"params\":{\"scale\":{\"gt\":1}}},\"target\":\"state.x\",\"value\":1}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"parameters\":{\"scale\":{\"type\":\"number\",\"default\":1}},\"effects\":[{\"when\":{\"params\":{\"scale\":{\"gt\":1}}},\"target\":\"state.x\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-llm", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"llm\":{\"prompt\":\"Answer YES or NO: is {{value}} auspicious?\",\"errorMessage\":\"The wire went dead.\"},\"effects\":[{\"when\":{\"llm\":{\"ok\":true}},\"target\":\"state.x\",\"value\":1}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"llm\":{\"prompt\":\"Answer YES or NO: is {{value}} auspicious?\",\"errorMessage\":\"The wire went dead.\"},\"effects\":[{\"when\":{\"llm\":{\"ok\":true}},\"target\":\"state.x\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-every-subject", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"parameters\":{\"scale\":{\"type\":\"number\",\"default\":1}},\"llm\":{\"prompt\":\"Answer YES or NO: is {{value}} auspicious?\",\"errorMessage\":\"The wire went dead.\"},\"effects\":[{\"when\":{\"gte\":0.5,\"roll\":{\"gt\":1},\"params\":{\"scale\":{\"eq\":2}},\"metadata\":{\"house\":{\"eq\":\"Aurum\"}},\"llm\":{\"ok\":true},\"outcome\":{\"eq\":\"success\"}},\"target\":\"state.x\",\"value\":1}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"parameters\":{\"scale\":{\"type\":\"number\",\"default\":1}},\"llm\":{\"prompt\":\"Answer YES or NO: is {{value}} auspicious?\",\"errorMessage\":\"The wire went dead.\"},\"effects\":[{\"when\":{\"gte\":0.5,\"roll\":{\"gt\":1},\"params\":{\"scale\":{\"eq\":2}},\"metadata\":{\"house\":{\"eq\":\"Aurum\"}},\"llm\":{\"ok\":true},\"outcome\":{\"eq\":\"success\"}},\"target\":\"state.x\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-subjects-written-backwards", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"llm\":{\"prompt\":\"Answer YES or NO: is {{value}} auspicious?\",\"errorMessage\":\"The wire went dead.\"},\"effects\":[{\"when\":{\"outcome\":{\"neq\":\"failure\"},\"llm\":{\"ok\":false},\"metadata\":{\"a\":{\"eq\":1}},\"roll\":{\"lt\":9},\"lte\":3},\"target\":\"metadata.y\",\"value\":true}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"llm\":{\"prompt\":\"Answer YES or NO: is {{value}} auspicious?\",\"errorMessage\":\"The wire went dead.\"},\"effects\":[{\"when\":{\"lte\":3,\"roll\":{\"lt\":9},\"metadata\":{\"a\":{\"eq\":1}},\"llm\":{\"ok\":false},\"outcome\":{\"neq\":\"failure\"}},\"target\":\"metadata.y\",\"value\":true}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-llm-ref-with-block", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"llm\":{\"prompt\":\"Answer YES or NO: is {{value}} auspicious?\",\"errorMessage\":\"The wire went dead.\"},\"effects\":[{\"target\":\"metadata.verdict\",\"value\":\"{{llm}}\"}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"llm\":{\"prompt\":\"Answer YES or NO: is {{value}} auspicious?\",\"errorMessage\":\"The wire went dead.\"},\"effects\":[{\"target\":\"metadata.verdict\",\"value\":\"{{llm}}\"}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-negative-literal", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.debt\",\"value\":-5}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"state.debt\",\"value\":-5}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-float-literal", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.ratio\",\"value\":0.25}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"state.ratio\",\"value\":0.25}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-target-metadata-dotted", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"metadata.ansible.tool\",\"value\":1}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"metadata.ansible.tool\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-target-bracket-index", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.crew[0].mood\",\"value\":\"'grim'\"}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"state.crew[0].mood\",\"value\":\"'grim'\"}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-target-underscore-deeper", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.encounter._notes\",\"value\":1}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"state.encounter._notes\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-target-at-cap", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\",\"value\":1}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"state.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-value-at-cap", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.x\",\"value\":\"'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy'\"}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"state.x\",\"value\":\"'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy'\"}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effects-at-cap", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.k0\",\"value\":1},{\"target\":\"state.k1\",\"value\":1},{\"target\":\"state.k2\",\"value\":1},{\"target\":\"state.k3\",\"value\":1},{\"target\":\"state.k4\",\"value\":1},{\"target\":\"state.k5\",\"value\":1},{\"target\":\"state.k6\",\"value\":1},{\"target\":\"state.k7\",\"value\":1},{\"target\":\"state.k8\",\"value\":1},{\"target\":\"state.k9\",\"value\":1},{\"target\":\"state.k10\",\"value\":1},{\"target\":\"state.k11\",\"value\":1},{\"target\":\"state.k12\",\"value\":1},{\"target\":\"state.k13\",\"value\":1},{\"target\":\"state.k14\",\"value\":1},{\"target\":\"state.k15\",\"value\":1}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"state.k0\",\"value\":1},{\"target\":\"state.k1\",\"value\":1},{\"target\":\"state.k2\",\"value\":1},{\"target\":\"state.k3\",\"value\":1},{\"target\":\"state.k4\",\"value\":1},{\"target\":\"state.k5\",\"value\":1},{\"target\":\"state.k6\",\"value\":1},{\"target\":\"state.k7\",\"value\":1},{\"target\":\"state.k8\",\"value\":1},{\"target\":\"state.k9\",\"value\":1},{\"target\":\"state.k10\",\"value\":1},{\"target\":\"state.k11\",\"value\":1},{\"target\":\"state.k12\",\"value\":1},{\"target\":\"state.k13\",\"value\":1},{\"target\":\"state.k14\",\"value\":1},{\"target\":\"state.k15\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effects-empty-array", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-many-mixed", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.a\",\"value\":1},{\"when\":{\"outcome\":{\"eq\":\"failure\"}},\"target\":\"metadata.b\",\"value\":false},{\"when\":{\"gte\":0.5},\"target\":\"state.c\",\"value\":\"{{value}} + 'x'\"}]}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"state.a\",\"value\":1},{\"when\":{\"outcome\":{\"eq\":\"failure\"}},\"target\":\"metadata.b\",\"value\":false},{\"when\":{\"gte\":0.5},\"target\":\"state.c\",\"value\":\"{{value}} + 'x'\"}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": []},
  {"kind": "definition", "id": "effect-bare-prose", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"metadata.lockpick\",\"value\":\"broken pick\"}]}", "success": false, "reason": "effects.0.value: value is not a valid expression: \"broken\" is a bare word — there are no identifiers here. Quote literal text ('broken') or use a {{ref}}", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-bad-prefix", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"somewhere.else\",\"value\":1}]}", "success": false, "reason": "effects.0.target: target must start with \"state.\" or \"metadata.\"", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-target-underscore-guard", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state._secrets.combo\",\"value\":1}]}", "success": false, "reason": "effects.0.target: target writes \"_secrets.combo\" — state keys starting with an underscore are user-only, and no tool may write them", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-target-state-empty", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.\",\"value\":1}]}", "success": false, "reason": "effects.0.target: target names no state path after \"state.\"", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-target-metadata-empty", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"metadata.\",\"value\":1}]}", "success": false, "reason": "effects.0.target: target names no metadata key after \"metadata.\"", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-target-empty-string", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"\",\"value\":1}]}", "success": false, "reason": "effects.0.target: Too small: expected string to have >=1 characters; effects.0.target: target must start with \"state.\" or \"metadata.\"", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-target-over-cap", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\",\"value\":1}]}", "success": false, "reason": "effects.0.target: Too big: expected string to have <=200 characters", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-target-missing", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"value\":1}]}", "success": false, "reason": "effects.0.target: Invalid input: expected string, received undefined", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-target-not-a-string", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":7,\"value\":1}]}", "success": false, "reason": "effects.0.target: Invalid input: expected string, received number", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-value-missing", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.x\"}]}", "success": false, "reason": "effects.0.value: Invalid input: expected number, received undefined — or — Invalid input: expected boolean, received undefined — or — Invalid input: expected string, received undefined", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-value-empty-string", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.x\",\"value\":\"\"}]}", "success": false, "reason": "effects.0.value: Too small: expected string to have >=1 characters; effects.0.value: value is not a valid expression: the expression is empty", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-value-over-cap", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.x\",\"value\":\"'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy'\"}]}", "success": false, "reason": "effects.0.value: Too big: expected string to have <=500 characters; effects.0.value: value is not a valid expression: the expression exceeds 500 characters", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-value-null", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.x\",\"value\":null}]}", "success": false, "reason": "effects.0.value: Invalid input: expected number, received null — or — Invalid input: expected boolean, received null — or — Invalid input: expected string, received null", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-value-object", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.x\",\"value\":{\"a\":1}}]}", "success": false, "reason": "effects.0.value: Invalid input: expected number, received object — or — Invalid input: expected boolean, received object — or — Invalid input: expected string, received object", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-value-array", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.x\",\"value\":[1]}]}", "success": false, "reason": "effects.0.value: Invalid input: expected number, received array — or — Invalid input: expected boolean, received array — or — Invalid input: expected string, received array", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-ghost-param", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.x\",\"value\":\"{{params.ghost}} + 1\"}]}", "success": false, "reason": "effects.0.value: value references undeclared parameter \"ghost\"", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-llm-ref-no-block", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"metadata.verdict\",\"value\":\"{{llm}}\"}]}", "success": false, "reason": "effects.0.value: value references {{llm}}, but the tool declares no `llm` block", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-llm-no-block", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"llm\":{\"ok\":true}},\"target\":\"state.x\",\"value\":1}]}", "success": false, "reason": "effects.0.when.llm: tests the LLM consult, but the tool declares no `llm` block", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-ghost-param", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"params\":{\"ghost\":{\"gt\":1}}},\"target\":\"state.x\",\"value\":1}]}", "success": false, "reason": "effects.0.when.params.ghost: tests undeclared parameter \"ghost\"", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-empty", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{},\"target\":\"state.x\",\"value\":1}]}", "success": false, "reason": "effects.0.when: must test something: a comparator on the value, `roll`, `llm`, `outcome`, a non-empty `params`, or a non-empty `metadata`", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-outcome-empty", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"outcome\":{}},\"target\":\"state.x\",\"value\":1}]}", "success": false, "reason": "effects.0.when.outcome: must test something: `eq` or `neq` against an outcome state", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-outcome-unknown-state", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"outcome\":{\"eq\":\"triumph\"}},\"target\":\"state.x\",\"value\":1}]}", "success": false, "reason": "effects.0.when.outcome.eq: Invalid option: expected one of \"success\"|\"partial\"|\"failure\"|\"info\"", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-outcome-unknown-key", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"outcome\":{\"is\":\"success\"}},\"target\":\"state.x\",\"value\":1}]}", "success": false, "reason": "effects.0.when.outcome: Unrecognized key: \"is\"", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-unknown-key", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"nonsense\":1},\"target\":\"state.x\",\"value\":1}]}", "success": false, "reason": "effects.0.when: Unrecognized key: \"nonsense\"", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-not-an-object", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":true,\"target\":\"state.x\",\"value\":1}]}", "success": false, "reason": "effects.0.when: Invalid input: expected object, received boolean", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-string-eq-on-value", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"eq\":\"brass\"},\"target\":\"state.x\",\"value\":1}]}", "success": false, "reason": "effects.0.when.eq: Invalid input: expected number, received string — or — Invalid input: expected object, received string — or — Invalid input: expected object, received string", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-contains-on-value", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"when\":{\"contains\":\"x\"},\"target\":\"state.x\",\"value\":1}]}", "success": false, "reason": "effects.0.when: Unrecognized key: \"contains\"", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-when-params-string-ordering", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"parameters\":{\"material\":{\"type\":\"string\",\"default\":\"brass\"}},\"effects\":[{\"when\":{\"params\":{\"material\":{\"gt\":1}}},\"target\":\"state.x\",\"value\":1}]}", "success": false, "reason": "effects.0.when.params.material.gt: gt orders parameter \"material\" against a number, and only numbers can be ordered", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-unknown-key", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.x\",\"value\":1,\"bogus\":true}]}", "success": false, "reason": "effects.0: Unrecognized key: \"bogus\"", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-not-an-object", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[1]}", "success": false, "reason": "effects.0: Invalid input: expected object, received number", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effects-not-an-array", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":{\"target\":\"state.x\",\"value\":1}}", "success": false, "reason": "effects: Invalid input: expected array, received object", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effects-past-cap", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.k0\",\"value\":1},{\"target\":\"state.k1\",\"value\":1},{\"target\":\"state.k2\",\"value\":1},{\"target\":\"state.k3\",\"value\":1},{\"target\":\"state.k4\",\"value\":1},{\"target\":\"state.k5\",\"value\":1},{\"target\":\"state.k6\",\"value\":1},{\"target\":\"state.k7\",\"value\":1},{\"target\":\"state.k8\",\"value\":1},{\"target\":\"state.k9\",\"value\":1},{\"target\":\"state.k10\",\"value\":1},{\"target\":\"state.k11\",\"value\":1},{\"target\":\"state.k12\",\"value\":1},{\"target\":\"state.k13\",\"value\":1},{\"target\":\"state.k14\",\"value\":1},{\"target\":\"state.k15\",\"value\":1},{\"target\":\"state.k16\",\"value\":1}]}", "success": false, "reason": "effects: at most 16 effects", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effects-past-cap-and-broken", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"nowhere0\",\"value\":1},{\"target\":\"nowhere1\",\"value\":1},{\"target\":\"nowhere2\",\"value\":1},{\"target\":\"nowhere3\",\"value\":1},{\"target\":\"nowhere4\",\"value\":1},{\"target\":\"nowhere5\",\"value\":1},{\"target\":\"nowhere6\",\"value\":1},{\"target\":\"nowhere7\",\"value\":1},{\"target\":\"nowhere8\",\"value\":1},{\"target\":\"nowhere9\",\"value\":1},{\"target\":\"nowhere10\",\"value\":1},{\"target\":\"nowhere11\",\"value\":1},{\"target\":\"nowhere12\",\"value\":1},{\"target\":\"nowhere13\",\"value\":1},{\"target\":\"nowhere14\",\"value\":1},{\"target\":\"nowhere15\",\"value\":1},{\"target\":\"nowhere16\",\"value\":1}]}", "success": false, "reason": "effects: at most 16 effects; effects.0.target: target must start with \"state.\" or \"metadata.\"; effects.1.target: target must start with \"state.\" or \"metadata.\"; effects.2.target: target must start with \"state.\" or \"metadata.\"; effects.3.target: target must start with \"state.\" or \"metadata.\"; effects.4.target: target must start with \"state.\" or \"metadata.\"; effects.5.target: target must start with \"state.\" or \"metadata.\"; effects.6.target: target must start with \"state.\" or \"metadata.\"; effects.7.target: target must start with \"state.\" or \"metadata.\"; effects.8.target: target must start with \"state.\" or \"metadata.\"; effects.9.target: target must start with \"state.\" or \"metadata.\"; effects.10.target: target must start with \"state.\" or \"metadata.\"; effects.11.target: target must start with \"state.\" or \"metadata.\"; effects.12.target: target must start with \"state.\" or \"metadata.\"; effects.13.target: target must start with \"state.\" or \"metadata.\"; effects.14.target: target must start with \"state.\" or \"metadata.\"; effects.15.target: target must start with \"state.\" or \"metadata.\"; effects.16.target: target must start with \"state.\" or \"metadata.\"", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-two-broken", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"nowhere\",\"value\":1},{\"target\":\"state.x\",\"value\":\"bare prose\"}]}", "success": false, "reason": "effects.0.target: target must start with \"state.\" or \"metadata.\"; effects.1.value: value is not a valid expression: \"bare\" is a bare word — there are no identifiers here. Quote literal text ('bare') or use a {{ref}}", "data": null, "unknownKeys": []},
  {"kind": "definition", "id": "effect-plus-unknown-top-level", "inputJson": "{\"name\":\"probe\",\"description\":\"A probe.\",\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}],\"effects\":[{\"target\":\"state.x\",\"value\":1}],\"persist\":true}", "success": true, "reason": null, "data": "{\"name\":\"probe\",\"description\":\"A probe.\",\"effects\":[{\"target\":\"state.x\",\"value\":1}],\"outcomes\":[{\"when\":true,\"message\":\"-\",\"state\":\"info\"}]}", "unknownKeys": ["persist"]},
  {"kind": "target", "id": "state-path", "target": "state.encounter.count", "ok": true, "parsed": "{\"kind\":\"state\",\"path\":[\"encounter\",\"count\"],\"raw\":\"state.encounter.count\"}", "reason": null},
  {"kind": "target", "id": "state-single", "target": "state.tally", "ok": true, "parsed": "{\"kind\":\"state\",\"path\":[\"tally\"],\"raw\":\"state.tally\"}", "reason": null},
  {"kind": "target", "id": "state-bracket", "target": "state.crew[0].mood", "ok": true, "parsed": "{\"kind\":\"state\",\"path\":[\"crew\",0,\"mood\"],\"raw\":\"state.crew[0].mood\"}", "reason": null},
  {"kind": "target", "id": "state-deep-underscore", "target": "state.encounter._notes", "ok": true, "parsed": "{\"kind\":\"state\",\"path\":[\"encounter\",\"_notes\"],\"raw\":\"state.encounter._notes\"}", "reason": null},
  {"kind": "target", "id": "state-underscore-guard", "target": "state._secrets.combo", "ok": false, "parsed": null, "reason": "writes \"_secrets.combo\" — state keys starting with an underscore are user-only, and no tool may write them"},
  {"kind": "target", "id": "state-empty", "target": "state.", "ok": false, "parsed": null, "reason": "names no state path after \"state.\""},
  {"kind": "target", "id": "state-spaces", "target": "state.the key", "ok": true, "parsed": "{\"kind\":\"state\",\"path\":[\"the\",\"key\"],\"raw\":\"state.the key\"}", "reason": null},
  {"kind": "target", "id": "metadata-whole-key", "target": "metadata.ansible.tool", "ok": true, "parsed": "{\"kind\":\"metadata\",\"key\":\"ansible.tool\",\"raw\":\"metadata.ansible.tool\"}", "reason": null},
  {"kind": "target", "id": "metadata-spaces", "target": "metadata.Clearance Level", "ok": true, "parsed": "{\"kind\":\"metadata\",\"key\":\"Clearance Level\",\"raw\":\"metadata.Clearance Level\"}", "reason": null},
  {"kind": "target", "id": "metadata-empty", "target": "metadata.", "ok": false, "parsed": null, "reason": "names no metadata key after \"metadata.\""},
  {"kind": "target", "id": "no-prefix", "target": "encounter.count", "ok": false, "parsed": null, "reason": "must start with \"state.\" or \"metadata.\""},
  {"kind": "target", "id": "empty", "target": "", "ok": false, "parsed": null, "reason": "must start with \"state.\" or \"metadata.\""},
  {"kind": "target", "id": "state-no-dot", "target": "state", "ok": false, "parsed": null, "reason": "must start with \"state.\" or \"metadata.\""},
  {"kind": "target", "id": "metadata-no-dot", "target": "metadata", "ok": false, "parsed": null, "reason": "must start with \"state.\" or \"metadata.\""},];

const definitionRows = CAPTURED.filter((r): r is DefinitionRow => r.kind === 'definition');
const targetRows = CAPTURED.filter((r): r is TargetRow => r.kind === 'target');

describe('chipLabel + effects — the captured v4 rows', () => {
  it('the table is the expected shape (a truncated capture must not pass silently)', () => {
    // Composition, never a hand-written count (`harness-corpus-shape-constants-
    // rot`): the partition is total, both kinds are non-empty, both verdicts
    // appear on each, and every row carries the half the replay reads.
    expect(definitionRows.length + targetRows.length).toBe(CAPTURED.length);
    expect(definitionRows.some((r) => r.success)).toBe(true);
    expect(definitionRows.some((r) => !r.success)).toBe(true);
    expect(targetRows.some((r) => r.ok)).toBe(true);
    expect(targetRows.some((r) => !r.ok)).toBe(true);
    expect(new Set(CAPTURED.map((r) => r.id)).size).toBe(CAPTURED.length);

    for (const row of definitionRows) {
      expect(typeof row.inputJson, row.id).toBe('string');
      expect(Array.isArray(row.unknownKeys), row.id).toBe(true);
      // An accepted row must carry the parsed bytes; a rejected one the
      // sentence. Either missing would compare against `null` and pass.
      expect(typeof (row.success ? row.data : row.reason), row.id).toBe('string');
    }
    for (const row of targetRows) {
      expect(typeof (row.ok ? row.parsed : row.reason), row.id).toBe('string');
    }
  });

  describe('safeParse', () => {
    for (const row of definitionRows) {
      it(`matches v4 — ${row.id}`, () => {
        const raw: unknown = JSON.parse(row.inputJson);

        expect(collectUnknownKeys(raw)).toEqual(row.unknownKeys);

        const result = safeParse(raw);

        if (result.success) {
          expect(row.success, `v5 accepted; v4 rejected with: ${row.reason}`).toBe(true);
          expect(JSON.stringify(result.data)).toBe(row.data);
        } else {
          const sentence = formatDefinitionIssues(result.issues);
          expect(row.success, `v5 rejected with: ${sentence}; v4 accepted`).toBe(false);
          expect(sentence).toBe(row.reason);
        }
      });
    }
  });

  describe('parseEffectTarget', () => {
    for (const row of targetRows) {
      it(`matches v4 — ${row.id}`, () => {
        const result = parseEffectTarget(row.target);
        if (result.ok) {
          expect(row.ok, `v5 parsed; v4 refused with: ${row.reason}`).toBe(true);
          expect(JSON.stringify(result.target)).toBe(row.parsed);
        } else {
          expect(row.ok, `v5 refused with: ${result.reason}; v4 parsed`).toBe(false);
          expect(result.reason).toBe(row.reason);
        }
      });
    }
  });
});
